import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Rubik_Gemstones,
  Inter,
  Comfortaa,
} from "next/font/google";
import "./globals.css";
import { Provider } from "@radix-ui/react-tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const GameFont = Rubik_Gemstones({
  subsets: ["latin"],
  variable: "--font-game",
  weight: "400",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: "400",
});

const comfortaa = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comfortaa",
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-background">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${GameFont.variable} ${inter.variable} ${comfortaa.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
